environment:
  ECLIPSE_URL: https://archive.eclipse.org/eclipse/downloads/drops/R-3.5.2-201002111343/eclipse-SDK-3.5.2-win32-x86_64.zip
  ECLIPSE_HASH: 4E9EDDD6DC4F69C8A02C105DCBAF1A2DEDED6BBED138557DBC598323BBAA0AD7
  EGIT_URL: https://archive.eclipse.org/egit/updates-2.1/org.eclipse.egit.repository-2.1.0.201209190230-r.zip
  EGIT_HASH: AF2D9B6D946B734D5BC232DCF58A5A40980CAE78DB5E12B66FCAF1A970535328

install:
  - cinst openjdk8 --version 8.232.9
  - cinst ant --version 1.10.5 --ignore-dependencies
before_build:
  - pwsh: scripts/prepare-eclipse.ps1 -EclipseUrl $env:ECLIPSE_URL -EclipseFileHash $env:ECLIPSE_HASH -EGitUrl $env:EGIT_URL -EGitFileHash $env:EGIT_HASH
build_script:
  - pwsh: scripts/build.ps1
on_finish:
  # upload test results
  - pwsh: |
      $wc = New-Object System.Net.WebClient
      Get-ChildItem build/output/bin/testresults/unittests -Recurse '*.xml' | Foreach-Object {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $_.FullName)
      }

skip_branch_with_pr: true

cache:
  - .build/downloads -> .appveyor.yml
  - .build/eclipse -> .appveyor.yml
  - C:/ProgramData/chocolatey/bin -> appveyor.yml
  - C:/ProgramData/chocolatey/lib -> appveyor.yml

artifacts:
  - path: build/output/bin/clc/TEE-CLC-1*.zip
    name: Client
  - path: build/output/bin/sdk/*.zip
    name: SDK
