environment:
  ECLIPSE_URL: https://archive.eclipse.org/eclipse/downloads/drops/R-3.5.2-201002111343/eclipse-SDK-3.5.2-win32-x86_64.zip
  ECLIPSE_HASH: 4E9EDDD6DC4F69C8A02C105DCBAF1A2DEDED6BBED138557DBC598323BBAA0AD7

install:
  - cinst ant
before_build:
  - pwsh: .appveyor/prepare-eclipse.ps1 -EclipseUrl $env:ECLIPSE_URL -EclipseHash $env:ECLIPSE_HASH
build_script:
  - pwsh: .appveyor/build.ps1

skip_branch_with_pr: true

cache:
  - .appveyor/downloads -> .appveyor.yml
  - .appveyor/eclipse -> .appveyor.yml
