install:
  - cinst openjdk8 --version 8.232.9
build_script:
  - pwsh: ./gradlew build --no-daemon
on_finish:
  # upload test results
  - pwsh: |
      $wc = New-Object System.Net.WebClient
      Get-ChildItem build/output/bin/testresults/unittests -Recurse '*.xml' | Foreach-Object {
          $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", $_.FullName)
      }

skip_branch_with_pr: true

cache:
  - .build/downloads -> .appveyor.yml
  - .build/eclipse -> .appveyor.yml
  - C:/ProgramData/chocolatey/bin -> .appveyor.yml
  - C:/ProgramData/chocolatey/lib -> .appveyor.yml

artifacts:
  - path: build/output/bin/clc/TEE-CLC-1*.zip
    name: Client
  - path: build/output/bin/sdk/*.zip
    name: SDK
