name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8.0.232+9.1'

      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: .build/downloads
          key: ${{ runner.os }}.downloads.${{ hashFiles('gradle.properties') }}
      - name: Cache Eclipse
        uses: actions/cache@v2
        with:
          path: .build/eclipse
          key: ${{ runner.os }}.eclipse.${{ hashFiles('gradle.properties') }}

      - name: Build
        shell: pwsh
        run: $env:PATH = "C:\Program Files\OpenJDK\openjdk-8u232-b09;$env:PATH"; $env:JAVA_HOME = "C:\Program Files\OpenJDK\openjdk-8u232-b09"; scripts/build.ps1

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: build/output/bin/testresults/unittests/*.xml

      - name: Upload CLC
        uses: actions/upload-artifact@v2
        with:
          name: Client
          path: build/output/bin/clc/TEE-CLC-1*.zip

      - name: Upload SDK
        uses: actions/upload-artifact@v2
        with:
          name: SDK
          path: build/output/bin/sdk/*.zip
