name: Main
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0'

jobs:
  main:
    runs-on: "windows-2022"
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8.0.232+9.1'

      - name: Cache downloads
        uses: actions/cache@v2
        with:
          path: build/downloads
          key: ${{ runner.os }}.downloads.${{ hashFiles('gradle.properties') }}
      - name: Cache Eclipse
        uses: actions/cache@v2
        with:
          path: build/eclipse
          key: ${{ runner.os }}.eclipse.${{ hashFiles('gradle.properties') }}

      - name: Build
        shell: pwsh
        run: ./gradlew build --no-daemon
        env:
          TEE_SERVER_URL: ${{ secrets.TEE_SERVER_URL }}
          TEE_TEAM_PROJECT: ${{ secrets.TEE_TEAM_PROJECT }}
          TEE_USER: ${{ secrets.TEE_USER }}
          TEE_PASS: ${{ secrets.TEE_PASS }}

      - name: Upload Ant test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results.ant
          path: build/output/bin/testresults/unittests/*.xml

      - name: Upload integration test results
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-results.integration
          path: integrationTests/build/reports

      - name: Upload CLC
        uses: actions/upload-artifact@v2
        with:
          name: Client
          path: build/output/bin/clc/TEE-CLC-1*.zip

      - name: Upload SDK
        uses: actions/upload-artifact@v2
        with:
          name: SDK
          path: build/output/bin/sdk/*.zip
